name: Validation

on:
  pull_request:
    branches:
      - "main"

env:
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
  POLLING_INTERVAL_SECONDS: 60
  RUN_TIMEOUT_MINUTES: 20
  MAX_CONCURRENT_WORKFLOWS: 2

jobs:
  lint:
    name: Metadata Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Node dependencies
        run: npm install -g ajv-cli

      - name: Validate items metadata styling
        run: |
          char_count_before_trim=$(cat items.yaml | wc -m)
          
          sed -i 's/[[:space:]]*$//' items.yaml

          char_count_after_trim=$(cat items.yaml | wc -m)
          char_count_diff=$(( $char_count_before_trim - $char_count_after_trim ))

          if [[ "$char_count_diff" -gt "0" ]]; then
              echo "items.yaml contains ${char_count_diff} trailing space(s) that must be trimmed"
              exit 1
          fi

      - name: Validate items metadata serialization
        run: |
          yq -o=json "items.yaml" > "items.json"

      - name: Validate items metadata contents
        run: |
          ajv validate -s schemas/items/v1alpha1.json -d items.json --spec=draft2020

  test-deploy-ansible-ecmwf:
    name: Ansible Playbook Testing (Native) on ECMWF
    runs-on: ubuntu-latest
    timeout-minutes: 100
    environment: ECMWF
    needs: lint

    steps:
      - name: Checkout catalog repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-ecmwf.yml"
          TOTAL_TIMEOUT_MINUTES: 90 # must be smaller than jobs.orchestrate.timeout-minutes
  
  test-deploy-ansible-eumetsat:
    name: Ansible Playbook Testing (Native) on EUMETSAT
    runs-on: ubuntu-latest
    timeout-minutes: 200
    environment: EUMETSAT
    needs: lint

    steps:
      - name: Checkout catalog repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-eumetsat.yml"
          TOTAL_TIMEOUT_MINUTES: 180 # must be smaller than jobs.orchestrate.timeout-minutes

  test-deploy-ansible-ecmwf-via-ewccli:
    name: Ansible Playbook Testing (via EWCCLI) on ECMWF
    runs-on: ubuntu-latest
    timeout-minutes: 100
    environment: ECMWF
    needs: test-deploy-ansible-ecmwf
    if: ${{ always() }}

    steps:
      - name: Checkout catalog repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable,EWCCLI-compatible"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-deployment-ansible-ecmwf.yml"
          TOTAL_TIMEOUT_MINUTES: 90 # must be smaller than jobs.orchestrate.timeout-minutes

  test-deploy-ansible-eumetsat-via-ewccli:
    name: Ansible Playbook Testing (via EWCCLI) on EUMETSAT
    runs-on: ubuntu-latest
    timeout-minutes: 200
    environment: EUMETSAT
    needs: test-deploy-ansible-eumetsat
    if: ${{ always() }}

    steps:
      - name: Checkout catalog repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install additional dependencies
        run: pip install -r .github/scripts/orchestrator/requirements.txt

      - name: Orchestrate deployments testing
        run: python .github/scripts/orchestrator/main.py
        env:
          ITEM_TECHNOLOGY_ANNOTATIONS: "Ansible Playbook"
          ITEM_OTHERS_ANNOTATIONS: "Deployable,EWCCLI-compatible"
          GH_DOWNSTREAM_WORKFLOW_FILE: "test-deployment-ansible-eumetsat.yml"
          TOTAL_TIMEOUT_MINUTES: 180 # must be smaller than jobs.orchestrate.timeout-minutes
